# Generated by Django 3.0.7 on 2020-06-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Justice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_service_duration', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='URLScraped',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=2000)),
                ('columns', models.CharField(max_length=2000)),
            ],
        ),
    ]
