# Generated by Django 3.0.7 on 2020-06-24 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlscraped',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
