# Generated by Django 3.0.7 on 2020-06-25 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200624_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlscraped',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
