# Generated by Django 3.0.7 on 2020-06-27 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_urlscraped_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlscraped',
            name='columns',
        ),
        migrations.AlterField(
            model_name='urlscraped',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
